# Generated by Django 5.0.6 on 2024-06-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dados_completos',
            field=models.BooleanField(default=False),
        ),
    ]
