# Generated by Django 5.0.6 on 2024-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_dados_completos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mudança_senha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='upload_foto',
            field=models.BooleanField(default=False),
        ),
    ]
