# Generated by Django 5.0.6 on 2024-06-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_mudança_senha_usuario_upload_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='mudança_senha',
            new_name='mudanca_senha',
        ),
    ]
