# Generated by Django 5.0.6 on 2024-06-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nivel_usuario',
            field=models.CharField(choices=[('1', 'Bronze'), ('2', 'Prata'), ('3', 'Ouro')], default='1', max_length=1),
        ),
    ]
