# Generated by Django 5.0.6 on 2024-06-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_nivel_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dados_validados',
            field=models.BooleanField(default=False),
        ),
    ]
