# Generated by Django 5.0.6 on 2024-06-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_dados_validados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
