# Generated by Django 5.0.6 on 2024-06-08 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_usuario_validador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
