# Generated by Django 5.0.6 on 2024-06-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_validacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
